# Kodawarione Company Manage
Kodawarione::Permission.new(permission_name: "kodawarione_company_manage_company_search" , action_name: "company_search" , permission_model_name: "Kodawarione::CompanyManage", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_company_manage", remark: "/kodawarione/company_manage/company_search").save
Kodawarione::Permission.new(permission_name: "kodawarione_company_manage_edit_commitment" , action_name: "edit_commitment" , permission_model_name: "Kodawarione::CompanyManage", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_company_manage", remark: "/kodawarione/company_manage/edit_commitment").save
Kodawarione::Permission.new(permission_name: "kodawarione_company_manage_update_commitment" , action_name: "update_commitment" , permission_model_name: "Kodawarione::CompanyManage", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_company_manage", remark: "/kodawarione/company_manage/update_commitment").save
Kodawarione::Permission.new(permission_name: "kodawarione_company_manage_edit_company" , action_name: "edit_company" , permission_model_name: "Kodawarione::CompanyManage", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_company_manage", remark: "/kodawarione/company_manage/edit_company").save
Kodawarione::Permission.new(permission_name: "kodawarione_company_manage_update_company" , action_name: "update_company" , permission_model_name: "Kodawarione::CompanyManage", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_company_manage", remark: "/kodawarione/company_manage/update_company").save
Kodawarione::Permission.new(permission_name: "kodawarione_company_manage_company_details_overview" , action_name: "company_details_overview" , permission_model_name: "Kodawarione::CompanyManage", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_company_manage", remark: "/kodawarione/company_manage/company_details_overview").save
Kodawarione::Permission.new(permission_name: "kodawarione_company_manage_company_details_basic_info" , action_name: "company_details_basic_info" , permission_model_name: "Kodawarione::CompanyManage", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_company_manage", remark: "/kodawarione/company_manage/company_details_basic_info").save
Kodawarione::Permission.new(permission_name: "kodawarione_company_manage_company_details_company_page" , action_name: "company_details_company_page" , permission_model_name: "Kodawarione::CompanyManage", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_company_manage", remark: "/kodawarione/company_manage/company_details_company_page").save
Kodawarione::Permission.new(permission_name: "kodawarione_company_manage_company_details_activity_page" , action_name: "company_details_activity_page" , permission_model_name: "Kodawarione::CompanyManage", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_company_manage", remark: "/kodawarione/company_manage/company_details_activity_page").save
Kodawarione::Permission.new(permission_name: "kodawarione_company_manage_favourite_student_list" , action_name: "favourite_student_list" , permission_model_name: "Kodawarione::CompanyManage", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_company_manage", remark: "/kodawarione/company_manage/company/favourite_student_list").save
Kodawarione::Permission.new(permission_name: "kodawarione_company_manage_join_event_list" , action_name: "join_event_list" , permission_model_name: "Kodawarione::CompanyManage", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_company_manage", remark: "/kodawarione/company_manage/company/join_event_list").save
Kodawarione::Permission.new(permission_name: "kodawarione_company_manage_company_event_list" , action_name: "company_event_list" , permission_model_name: "Kodawarione::CompanyManage", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_company_manage", remark: "/kodawarione/company_manage/company/company_event_list").save
Kodawarione::Permission.new(permission_name: "kodawarione_company_manage_company_vacancy_list" , action_name: "company_vacancy_list" , permission_model_name: "Kodawarione::CompanyManage", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_company_manage", remark: "/kodawarione/company_manage/company/company_vacancy_list").save

# Kodawarione Event
Kodawarione::Permission.new(permission_name: "kodawarione_event_event_list" , action_name: "event_list" , permission_model_name: "Kodawarione::Event", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_event_manage", remark: "/kodawarione/event_list").save
Kodawarione::Permission.new(permission_name: "kodawarione_event_show" , action_name: "read" , permission_model_name: "Kodawarione::Event", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_event_manage", remark: "/kodawarione/show/:id").save
Kodawarione::Permission.new(permission_name: "kodawarione_event_new" , action_name: "create" , permission_model_name: "Kodawarione::Event", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_event_manage", remark: "/kodawarione/[new,create]").save
Kodawarione::Permission.new(permission_name: "kodawarione_event_event_edit" , action_name: "event_edit" , permission_model_name: "Kodawarione::Event", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_event_manage", remark: "/kodawarione/event_edit").save
Kodawarione::Permission.new(permission_name: "kodawarione_event_admin_self_event_update" , action_name: "admin_self_event_update" , permission_model_name: "Kodawarione::Event", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_event_manage", remark: "/kodawarione/admin_self_event_update").save
Kodawarione::Permission.new(permission_name: "kodawarione_event_admin_self_event_delete" , action_name: "admin_self_event_delete" , permission_model_name: "Kodawarione::Event", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_event_manage", remark: "/kodawarione/admin_self_event_delete").save
Kodawarione::Permission.new(permission_name: "kodawarione_event_event_joined_by_spu" , action_name: "event_joined_by_spu" , permission_model_name: "Kodawarione::Event", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_event_manage", remark: "/kodawarione/event_joined_by_spu").save
Kodawarione::Permission.new(permission_name: "kodawarione_event_event_joined_by_user" , action_name: "event_joined_by_user" , permission_model_name: "Kodawarione::Event", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_event_manage", remark: "/kodawarione/event_joined_by_user").save
Kodawarione::Permission.new(permission_name: "kodawarione_event_event_joined_by_partner" , action_name: "event_joined_by_partner" , permission_model_name: "Kodawarione::Event", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_event_manage", remark: "/kodawarione/event_joined_by_partner").save
Kodawarione::Permission.new(permission_name: "kodawarione_event_event_joined_by_company" , action_name: "event_joined_by_company" , permission_model_name: "Kodawarione::Event", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_event_manage", remark: "/kodawarione/event_joined_by_company").save

# Kodawarione Event Manage
Kodawarione::Permission.new(permission_name: "kodawarione_event_manage_search_event" , action_name: "search_event" , permission_model_name: "Kodawarione::EventManage", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_event_manage", remark: "/kodawarione/event_manage/search_event").save
Kodawarione::Permission.new(permission_name: "kodawarione_event_manage_search_event_detail" , action_name: "search_event_detail" , permission_model_name: "Kodawarione::EventManage", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_event_manage", remark: "/kodawarione/event_manage/search_event_detail/:id").save
Kodawarione::Permission.new(permission_name: "kodawarione_event_manage_event_apply_student_list" , action_name: "event_apply_student_list" , permission_model_name: "Kodawarione::EventManage", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_event_manage", remark: "/kodawarione/event_manage/event_apply_student_list/:id").save

# Kodawarione Partner Manage
Kodawarione::Permission.new(permission_name: "kodawarione_partner_manage_index" , action_name: "read" , permission_model_name: "Kodawarione::Partner", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_partner_manage", remark: "/kodawarione/partner_manage/[index,show]").save
Kodawarione::Permission.new(permission_name: "kodawarione_partner_manage_partner_details" , action_name: "partner_details" , permission_model_name: "Kodawarione::Partner", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_partner_manage", remark: "/kodawarione/partner_manage/partner_details/:id").save
Kodawarione::Permission.new(permission_name: "kodawarione_partner_manage_partner_member_list" , action_name: "partner_member_list" , permission_model_name: "Kodawarione::Partner", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_partner_manage", remark: "/kodawarione/partner_manage/partner_member_list").save
Kodawarione::Permission.new(permission_name: "kodawarione_partner_manage_edit_partner_details" , action_name: "edit_partner_details" , permission_model_name: "Kodawarione::Partner", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_partner_manage", remark: "/kodawarione/partner_manage/edit_partner_details/:id").save
Kodawarione::Permission.new(permission_name: "kodawarione_partner_manage_update_partner_details" , action_name: "update_partner_details" , permission_model_name: "Kodawarione::Partner", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_partner_manage", remark: "/kodawarione/partner_manage/update_partner_details/:id").save
Kodawarione::Permission.new(permission_name: "kodawarione_partner_manage_edit_partner_member_setup" , action_name: "edit_partner_member_setup" , permission_model_name: "Kodawarione::Partner", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_partner_manage", remark: "/kodawarione/partner_manage/edit_partner_member_setup/:id").save
Kodawarione::Permission.new(permission_name: "kodawarione_partner_manage_show_partner_member_setup" , action_name: "show_partner_member_setup" , permission_model_name: "Kodawarione::Partner", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_partner_manage", remark: "/kodawarione/partner_manage/show_partner_member_setup/:id").save
Kodawarione::Permission.new(permission_name: "kodawarione_partner_manage_update_partner_member_setup" , action_name: "update_partner_member_setup" , permission_model_name: "Kodawarione::Partner", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_partner_manage", remark: "/kodawarione/partner_manage/update_partner_member_setup/:id").save
Kodawarione::Permission.new(permission_name: "kodawarione_partner_manage_new_partner_member_setup" , action_name: "new_partner_member_setup" , permission_model_name: "Kodawarione::Partner", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_partner_manage", remark: "/kodawarione/partner_manage/new_partner_member_setup").save
Kodawarione::Permission.new(permission_name: "kodawarione_partner_manage_create_partner_member_setup" , action_name: "create_partner_member_setup" , permission_model_name: "Kodawarione::Partner", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_partner_manage", remark: "/kodawarione/partner_manage/create_partner_member_setup").save
Kodawarione::Permission.new(permission_name: "kodawarione_partner_manage_destroy_partner_member" , action_name: "destroy_partner_member" , permission_model_name: "Kodawarione::Partner", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_partner_manage", remark: "/kodawarione/partner_manage/destroy_partner_member").save

# Kodawarione Partner Partner Create Step
Kodawarione::Permission.new(permission_name: "kodawarione_partner_manage_index" , action_name: "read" , permission_model_name: "Kodawarione::PartnerStep", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_partner_create_step", remark: "/kodawarione/partner_manage/[index,show]").save
Kodawarione::Permission.new(permission_name: "kodawarione_partner_manage_partner_step_new" , action_name: "create" , permission_model_name: "Kodawarione::PartnerStep", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_partner_create_step", remark: "/kodawarione/partner_manage/partner_steps/[new,create]").save
Kodawarione::Permission.new(permission_name: "kodawarione_partner_manage_partner_step_update" , action_name: "update" , permission_model_name: "Kodawarione::PartnerStep", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_partner_create_step", remark: "/kodawarione/partner_manage/partner_steps/:id/[update]").save

# Kodawarione Student Manage
Kodawarione::Permission.new(permission_name: "kodawarione_student_manage_search_student" , action_name: "search_student" , permission_model_name: "Kodawarione::StudentManage", permission_for: 1, permission_default_can: false, permission_group: "student_manage", remark: "/kodawarione/student_manage/search_student").save
Kodawarione::Permission.new(permission_name: "kodawarione_student_manage_edit_commitment" , action_name: "edit_commitment" , permission_model_name: "Kodawarione::StudentManage", permission_for: 1, permission_default_can: false, permission_group: "student_manage", remark: "/kodawarione/student_manage/edit_commitment").save
Kodawarione::Permission.new(permission_name: "kodawarione_student_manage_update_commitment" , action_name: "update_commitment" , permission_model_name: "Kodawarione::StudentManage", permission_for: 1, permission_default_can: false, permission_group: "student_manage", remark: "/kodawarione/student_manage/update_commitment").save
Kodawarione::Permission.new(permission_name: "kodawarione_student_manage_edit_student_detail" , action_name: "edit_student_detail" , permission_model_name: "Kodawarione::StudentManage", permission_for: 1, permission_default_can: false, permission_group: "student_manage", remark: "/kodawarione/student_manage/edit_student_detail").save
Kodawarione::Permission.new(permission_name: "kodawarione_student_manage_update_student_detail" , action_name: "update_student_detail" , permission_model_name: "Kodawarione::StudentManage", permission_for: 1, permission_default_can: false, permission_group: "student_manage", remark: "/kodawarione/student_manage/update_student_detail").save
Kodawarione::Permission.new(permission_name: "kodawarione_student_manage_student_details" , action_name: "student_details" , permission_model_name: "Kodawarione::StudentManage", permission_for: 1, permission_default_can: false, permission_group: "student_manage", remark: "/kodawarione/student_manage/search_student_details/:id").save
Kodawarione::Permission.new(permission_name: "kodawarione_student_manage_overview" , action_name: "overview" , permission_model_name: "Kodawarione::StudentManage", permission_for: 1, permission_default_can: false, permission_group: "student_manage", remark: "/kodawarione/student_manage/overview/:id").save
Kodawarione::Permission.new(permission_name: "kodawarione_student_manage_assessment" , action_name: "assessment" , permission_model_name: "Kodawarione::StudentManage", permission_for: 1, permission_default_can: false, permission_group: "student_manage", remark: "/kodawarione/student_manage/assessment/:id").save
Kodawarione::Permission.new(permission_name: "kodawarione_student_apply_vacancy_list" , action_name: "apply_vacancy_list" , permission_model_name: "Kodawarione::StudentManage", permission_for: 1, permission_default_can: false, permission_group: "student_manage", remark: "/kodawarione/student_manage/student/apply_vacancy_list/:id").save
Kodawarione::Permission.new(permission_name: "kodawarione_student_favourite_vacancy_list" , action_name: "favourite_vacancy_list" , permission_model_name: "Kodawarione::StudentManage", permission_for: 1, permission_default_can: false, permission_group: "student_manage", remark: "/kodawarione/student_manage/student/favourite_vacancy_list/:id").save
Kodawarione::Permission.new(permission_name: "kodawarione_student_favourite_company_list" , action_name: "favourite_company_list" , permission_model_name: "Kodawarione::StudentManage", permission_for: 1, permission_default_can: false, permission_group: "student_manage", remark: "/kodawarione/student_manage/student/favourite_company_list/:id").save
Kodawarione::Permission.new(permission_name: "kodawarione_student_join_event_list" , action_name: "join_event_list" , permission_model_name: "Kodawarione::StudentManage", permission_for: 1, permission_default_can: false, permission_group: "student_manage", remark: "/kodawarione/student_manage/student/join_event_list/:id").save
Kodawarione::Permission.new(permission_name: "kodawarione_student_favourite_event_list" , action_name: "favourite_event_list" , permission_model_name: "Kodawarione::StudentManage", permission_for: 1, permission_default_can: false, permission_group: "student_manage", remark: "/kodawarione/student_manage/student/favourite_event_list/:id").save

# Kodawarione Super Partner Create Step
Kodawarione::Permission.new(permission_name: "kodawarione_super_partner_manage_index" , action_name: "read" , permission_model_name: "Kodawarione::SuperPartnerStep", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_super_partner_create_step", remark: "/kodawarione/super_partner_manage/[index,show]").save
Kodawarione::Permission.new(permission_name: "kodawarione_super_partner_manage_super_partner_step_new" , action_name: "create" , permission_model_name: "Kodawarione::SuperPartnerStep", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_super_partner_create_step", remark: "/kodawarione/super_partner_manage/super_partner_steps/[new,create]").save
Kodawarione::Permission.new(permission_name: "kodawarione_super_partner_manage_super_partner_step_update" , action_name: "update" , permission_model_name: "Kodawarione::SuperPartnerStep", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_super_partner_create_step", remark: "/kodawarione/super_partner_manage/super_partner_steps/:id/[update]").save

# Kodawarione Super Partner Manage
Kodawarione::Permission.new(permission_name: "kodawarione_super_partner_manage_index" , action_name: "read" , permission_model_name: "Kodawarione::SuperPartner", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_super_partner_manage", remark: "/kodawarione/super_partner_manage/[index,show]").save
Kodawarione::Permission.new(permission_name: "kodawarione_super_partner_manage_super_partner_details" , action_name: "super_partner_details" , permission_model_name: "Kodawarione::SuperPartner", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_super_partner_manage", remark: "/kodawarione/super_partner_manage/super_partner_details/:id").save
Kodawarione::Permission.new(permission_name: "kodawarione_super_partner_manage_edit_super_partner_details" , action_name: "edit_super_partner_details" , permission_model_name: "Kodawarione::SuperPartner", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_super_partner_manage", remark: "/kodawarione/super_partner_manage/edit_super_partner_details/:id").save
Kodawarione::Permission.new(permission_name: "kodawarione_super_partner_manage_update_super_partner_details" , action_name: "update_super_partner_details" , permission_model_name: "Kodawarione::SuperPartner", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_super_partner_manage", remark: "/kodawarione/super_partner_manage/update_super_partner_details/:id").save
Kodawarione::Permission.new(permission_name: "kodawarione_super_partner_manage_super_partner_member_list" , action_name: "super_partner_member_list" , permission_model_name: "Kodawarione::SuperPartner", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_super_partner_manage", remark: "/kodawarione/super_partner_manage/super_partner_member_list/:id").save
Kodawarione::Permission.new(permission_name: "kodawarione_super_partner_manage_new_super_partner_member_setup" , action_name: "new_super_partner_member_setup" , permission_model_name: "Kodawarione::SuperPartner", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_super_partner_manage", remark: "/kodawarione/super_partner_manage/new_super_partner_member_setup/:id").save
Kodawarione::Permission.new(permission_name: "kodawarione_super_partner_manage_create_super_partner_member_setup" , action_name: "create_super_partner_member_setup" , permission_model_name: "Kodawarione::SuperPartner", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_super_partner_manage", remark: "/kodawarione/super_partner_manage/create_super_partner_member_setup/:id").save
Kodawarione::Permission.new(permission_name: "kodawarione_super_partner_manage_show_super_partner_member_setup" , action_name: "show_super_partner_member_setup" , permission_model_name: "Kodawarione::SuperPartner", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_super_partner_manage", remark: "/kodawarione/super_partner_manage/show_super_partner_member_setup/:id").save
Kodawarione::Permission.new(permission_name: "kodawarione_super_partner_manage_edit_super_partner_member_setup" , action_name: "edit_super_partner_member_setup" , permission_model_name: "Kodawarione::SuperPartner", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_super_partner_manage", remark: "/kodawarione/super_partner_manage/edit_super_partner_member_setup/:id").save
Kodawarione::Permission.new(permission_name: "kodawarione_super_partner_manage_update_super_partner_member_setup" , action_name: "update_super_partner_member_setup" , permission_model_name: "Kodawarione::SuperPartner", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_super_partner_manage", remark: "/kodawarione/super_partner_manage/update_super_partner_member_setup/:id").save
Kodawarione::Permission.new(permission_name: "kodawarione_super_partner_manage_destroy_super_partner_member" , action_name: "destroy_super_partner_member" , permission_model_name: "Kodawarione::SuperPartner", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_super_partner_manage", remark: "/kodawarione/super_partner_manage/destroy_super_partner_member/:id").save

# Kodawarione Vacancy Manage
Kodawarione::Permission.new(permission_name: "kodawarione_vacancy_manage_search_vacancy" , action_name: "search_vacancy" , permission_model_name: "Company::Vacancy", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_vacancy_manage", remark: "/kodawarione/vacancy_manage/search_vacancy").save
Kodawarione::Permission.new(permission_name: "kodawarione_vacancy_manage_search_vacancy_detail" , action_name: "search_vacancy_detail" , permission_model_name: "Company::Vacancy", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_vacancy_manage", remark: "/kodawarione/vacancy_manage/search_vacancy_detail/:id").save
Kodawarione::Permission.new(permission_name: "kodawarione_vacancy_manage_vacancy_applied_student_list" , action_name: "vacancy_applied_student_list" , permission_model_name: "Company::Vacancy", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_vacancy_manage", remark: "/kodawarione/vacancy_manage/vacancy_applied_student_list/:id").save

# Kodawarione Dashboard Manage
Kodawarione::Permission.new(permission_name: "kodawarione_dashboard_index" , action_name: "read" , permission_model_name: "Kodawarione::Dashboard", permission_for: 1, permission_default_can: true, permission_group: "kodawarione_dashboard_index", remark: "/kodawarione/dashboard/index").save

# Kodawarione Setting Manage
Kodawarione::Permission.new(permission_name: "kodawarione_kodawari_setting" , action_name: "kodawari_setting" , permission_model_name: "Kodawarione::Setting", permission_for: 1, permission_default_can: true, permission_group: "kodawarione_kodawari_setting", remark: "/kodawarione/kodawari_setting").save
Kodawarione::Permission.new(permission_name: "kodawarione_password_update" , action_name: "password_update" , permission_model_name: "Kodawarione::Setting", permission_for: 1, permission_default_can: true, permission_group: "kodawarione_kodawari_setting", remark: "/kodawarione/password_update").save

# Kodawarione Admin Roles Manage
Kodawarione::Permission.new(permission_name: "kodawarione_admin_roles_index" , action_name: "read" , permission_model_name: "Kodawarione::AdminRole", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_admin_roles_manage", remark: "/kodawarione/admin_roles/[index,show]").save
Kodawarione::Permission.new(permission_name: "kodawarione_admin_roles_new" , action_name: "create" , permission_model_name: "Kodawarione::AdminRole", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_admin_roles_manage", remark: "/kodawarione/admin_roles/[new,create]").save
Kodawarione::Permission.new(permission_name: "kodawarione_admin_roles_edit" , action_name: "update" , permission_model_name: "Kodawarione::AdminRole", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_admin_roles_manage", remark: "/kodawarione/admin_roles/:id/[edit,update]").save
Kodawarione::Permission.new(permission_name: "kodawarione_admin_roles_permission_categories" , action_name: "permission_categories" , permission_model_name: "Kodawarione::AdminRole", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_admin_roles_manage", remark: "/kodawarione/permission_categories").save
Kodawarione::Permission.new(permission_name: "kodawarione_admin_roles_permission_data" , action_name: "permission_data" , permission_model_name: "Kodawarione::AdminRole", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_admin_roles_manage", remark: "/kodawarione/permission_data").save
Kodawarione::Permission.new(permission_name: "kodawarione_admin_roles_save_role_permission" , action_name: "save_role_permission" , permission_model_name: "Kodawarione::AdminRole", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_admin_roles_manage", remark: "/kodawarione/save_role_permission").save
Kodawarione::Permission.new(permission_name: "kodawarione_admin_roles_destroy" , action_name: "destroy" , permission_model_name: "Kodawarione::AdminRole", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_admin_roles_manage", remark: "/kodawarione/admin_roles/:id").save

# Kodawarione Admin Contracts Manage
Kodawarione::Permission.new(permission_name: "kodawarione_contracts_index" , action_name: "read" , permission_model_name: "Kodawarione::Contract", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_contracts_manage", remark: "/kodawarione/contracts/[index,show]").save
Kodawarione::Permission.new(permission_name: "kodawarione_contracts_new" , action_name: "create" , permission_model_name: "Kodawarione::Contract", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_contracts_manage", remark: "/kodawarione/contracts/[new,create]").save
Kodawarione::Permission.new(permission_name: "kodawarione_contracts_edit" , action_name: "update" , permission_model_name: "Kodawarione::Contract", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_contracts_manage", remark: "/kodawarione/contracts/:id/[edit,update]").save
Kodawarione::Permission.new(permission_name: "kodawarione_contracts_destroy" , action_name: "destroy" , permission_model_name: "Kodawarione::Contract", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_contracts_manage", remark: "/kodawarione/contracts/:id").save

# Kodawarione Admin News Manage
Kodawarione::Permission.new(permission_name: "kodawarione_news_index" , action_name: "read" , permission_model_name: "Kodawarione::News", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_news_manage", remark: "/kodawarione/news/[index,show]").save
Kodawarione::Permission.new(permission_name: "kodawarione_news_new" , action_name: "create" , permission_model_name: "Kodawarione::News", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_news_manage", remark: "/kodawarione/news/[new,create]").save
Kodawarione::Permission.new(permission_name: "kodawarione_news_edit" , action_name: "update" , permission_model_name: "Kodawarione::News", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_news_manage", remark: "/kodawarione/news/:id/[edit,update]").save
Kodawarione::Permission.new(permission_name: "kodawarione_news_destroy" , action_name: "destroy" , permission_model_name: "Kodawarione::News", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_news_manage", remark: "/kodawarione/news/:id").save

# Kodawarione Admin Plans Manage
Kodawarione::Permission.new(permission_name: "kodawarione_plans_index" , action_name: "read" , permission_model_name: "Kodawarione::Plan", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_plans_manage", remark: "/kodawarione/plans/[index,show]").save
Kodawarione::Permission.new(permission_name: "kodawarione_plans_new" , action_name: "create" , permission_model_name: "Kodawarione::Plan", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_plans_manage", remark: "/kodawarione/plans/[new,create]").save
Kodawarione::Permission.new(permission_name: "kodawarione_plans_edit" , action_name: "update" , permission_model_name: "Kodawarione::Plan", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_plans_manage", remark: "/kodawarione/plans/:id/[edit,update]").save
Kodawarione::Permission.new(permission_name: "kodawarione_plans_destroy" , action_name: "destroy" , permission_model_name: "Kodawarione::Plan", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_plans_manage", remark: "/kodawarione/plans/:id").save

# Kodawarione Company Roles Manage
Kodawarione::Permission.new(permission_name: "kodawarione_company_roles_index" , action_name: "read" , permission_model_name: "Kodawarione::CompanyRole", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_company_roles_manage", remark: "/kodawarione/company_roles/[index,show]").save
Kodawarione::Permission.new(permission_name: "kodawarione_company_roles_new" , action_name: "create" , permission_model_name: "Kodawarione::CompanyRole", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_company_roles_manage", remark: "/kodawarione/company_roles/[new,create]").save
Kodawarione::Permission.new(permission_name: "kodawarione_company_roles_edit" , action_name: "update" , permission_model_name: "Kodawarione::CompanyRole", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_company_roles_manage", remark: "/kodawarione/company_roles/:id/[edit,update]").save
Kodawarione::Permission.new(permission_name: "kodawarione_company_roles_permission_categories" , action_name: "permission_categories" , permission_model_name: "Kodawarione::CompanyRole", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_company_roles_manage", remark: "/kodawarione/company_permission_categories").save
Kodawarione::Permission.new(permission_name: "kodawarione_company_roles_permission_data" , action_name: "permission_data" , permission_model_name: "Kodawarione::CompanyRole", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_company_roles_manage", remark: "/kodawarione/company_permission_data").save
Kodawarione::Permission.new(permission_name: "kodawarione_company_roles_save_role_permission" , action_name: "save_role_permission" , permission_model_name: "Kodawarione::CompanyRole", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_company_roles_manage", remark: "/kodawarione/save_role_permission").save
Kodawarione::Permission.new(permission_name: "kodawarione_company_roles_destroy" , action_name: "destroy" , permission_model_name: "Kodawarione::CompanyRole", permission_for: 1, permission_default_can: false, permission_group: "kodawarione_company_roles_manage", remark: "/kodawarione/company_roles/:id").save
