Company::MCompanyQuestionnaire.create!(id:1, questionnaire_title:'成長／安定',questionnaire_content: 'これからの会社の目指す方向性についてです。 事業規模を拡大し成長していくことを目指しますか？ それとも、事業内容を充実し安定した経営を目指しますか？',delete_flg: false, basic_point: 10, stages: 3)
Company::MCompanyQuestionnaire.create!(id:2, questionnaire_title:'主な採用方針',questionnaire_content: '主な採用方針についてです。 適正をしっかり見極めて配属する総合職採用ですか？ それとも、専門性を活かして活躍できる職種（ジョブ型）採用ですか？ ',delete_flg: false, basic_point: 10, stages: 3)
Company::MCompanyQuestionnaire.create!(id:3, questionnaire_title:'人事評価',questionnaire_content: '人事評価における重点についてです。 会社への貢献を明確に評価する成果を重視しますか？ それとも、中長期での貢献を公平に評価するプロセスを重視しますか？',delete_flg: false, basic_point: 10, stages: 3)
Company::MCompanyQuestionnaire.create!(id:4, questionnaire_title:'社員利益',questionnaire_content: 'あたなの会社が社員に提供できる利益で重要と考えるのはどちらですか？',delete_flg: false, basic_point: 10, stages: 2)
Company::MCompanyQuestionnaire.create!(id:5, questionnaire_title:'対象エリア',questionnaire_content: '事業で主に対象としているエリアについて選択してください。',delete_flg: false, basic_point: 10, stages: 3)
Company::MCompanyQuestionnaire.create!(id:6, questionnaire_title:'事業の発展',questionnaire_content: '事業の発展における方向性についてです。 イノベーション創出を通した新規事業の開拓を積極的におこないますか？ それとも、現在の事業品質を高め堅実な発展を目指しますか？',delete_flg: false, basic_point: 10, stages: 1)
Company::MCompanyQuestionnaire.create!(id:7, questionnaire_title:'社風',questionnaire_content: 'あなたの会社のアピールできる社風はどちらですか？',delete_flg: false, basic_point: 10, stages: 3)
Company::MCompanyQuestionnaire.create!(id:8, questionnaire_title:'育成方法',questionnaire_content: '社員の育成方法で重視することについてです。 ジョブローテーションによる多様な経験を重視しますか？ それとも、分野に特化した専門スキルの習得を重視しますか？',delete_flg: false, basic_point: 10, stages: 1)


Student::MStudentQuestionnaire.create!(id:1, questionnaire_title:'企業方針',questionnaire_content: '',delete_flg: false, basic_point: 10, stages: 3)
Student::MStudentQuestionnaire.create!(id:2, questionnaire_title:'採用方法',questionnaire_content: '',delete_flg: false, basic_point: 10, stages: 3)
Student::MStudentQuestionnaire.create!(id:3, questionnaire_title:'評価制度',questionnaire_content: '',delete_flg: false, basic_point: 10, stages: 3)
Student::MStudentQuestionnaire.create!(id:4, questionnaire_title:'社員利益',questionnaire_content: '',delete_flg: false, basic_point: 10, stages: 2)
Student::MStudentQuestionnaire.create!(id:5, questionnaire_title:'事業展開',questionnaire_content: '',delete_flg: false, basic_point: 10, stages: 3)
Student::MStudentQuestionnaire.create!(id:6, questionnaire_title:'事業発展',questionnaire_content: '',delete_flg: false, basic_point: 10, stages: 1)
Student::MStudentQuestionnaire.create!(id:7, questionnaire_title:'社風',questionnaire_content: '',delete_flg: false, basic_point: 10, stages: 3)
Student::MStudentQuestionnaire.create!(id:8, questionnaire_title:'スキルアップ',questionnaire_content: '',delete_flg: false, basic_point: 10, stages: 1)


QuestionnaireAnswer.create!(id:1, questionnaire_id:1, questionnaire_answer:'会社の成長性 ・将来性', delete_flg: false)
QuestionnaireAnswer.create!(id:2, questionnaire_id:1, questionnaire_answer:'会社の安定性・持続性', delete_flg: false)
QuestionnaireAnswer.create!(id:3, questionnaire_id:2, questionnaire_answer:'職種別（ジョブ型）採用', delete_flg: false)
QuestionnaireAnswer.create!(id:4, questionnaire_id:2, questionnaire_answer:'総合職採用', delete_flg: false)
QuestionnaireAnswer.create!(id:5, questionnaire_id:3, questionnaire_answer:'成果重視', delete_flg: false)
QuestionnaireAnswer.create!(id:6, questionnaire_id:3, questionnaire_answer:'プロセス重視', delete_flg: false)
QuestionnaireAnswer.create!(id:7, questionnaire_id:4, questionnaire_answer:'仕事のやりがい', delete_flg: false)
QuestionnaireAnswer.create!(id:8, questionnaire_id:4, questionnaire_answer:'給与・福利厚生・労働時間等の満足度', delete_flg: false)
QuestionnaireAnswer.create!(id:9, questionnaire_id:5, questionnaire_answer:'グローバル志向', delete_flg: false)
QuestionnaireAnswer.create!(id:10, questionnaire_id:5, questionnaire_answer:'地元または国内志向', delete_flg: false)
QuestionnaireAnswer.create!(id:11, questionnaire_id:6, questionnaire_answer:'イノベーションへの挑戦', delete_flg: false)
QuestionnaireAnswer.create!(id:12, questionnaire_id:6, questionnaire_answer:'現業の堅実な発展', delete_flg: false)
QuestionnaireAnswer.create!(id:13, questionnaire_id:7, questionnaire_answer:'活気のある職場', delete_flg: false)
QuestionnaireAnswer.create!(id:14, questionnaire_id:7, questionnaire_answer:'社員の相互尊重', delete_flg: false)
QuestionnaireAnswer.create!(id:15, questionnaire_id:8, questionnaire_answer:'分野に特化した専門スキルの習得', delete_flg: false)
QuestionnaireAnswer.create!(id:16, questionnaire_id:8, questionnaire_answer:'ジョブローテーションによる多様な経験', delete_flg: false)