# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Admin.create!(email: "admin@kodawarione.com",password: "admin123",admin_code: "BL000001",last_name: "Admin",first_name: "Admin",user_type: 0,confirmed_at: Faker::Time.backward(days: 1))
Partner::Partner.create!(name: "Other",partner_code: "9999",postal_code: nil,address: nil,display_address: "nil",phone_no: "00000000000", website_url: nil,postalcode_city: "北海道", m_region_id: 0, m_prefecture_id: 0)

#Industry data seed start (New Industry)
MIndustry.create!(industry_name: "水産・農林")
MIndustry.create!(industry_name: "食品")
MIndustry.create!(industry_name: "建設・住宅")
MIndustry.create!(industry_name: "アパレル・服飾関連")
MIndustry.create!(industry_name: "医薬品")
MIndustry.create!(industry_name: "化粧品")
MIndustry.create!(industry_name: "化学")
MIndustry.create!(industry_name: "石油")
MIndustry.create!(industry_name: "ガラス・セラミックス")
MIndustry.create!(industry_name: "ゴム")
MIndustry.create!(industry_name: "紙")
MIndustry.create!(industry_name: "繊維")
MIndustry.create!(industry_name: "鉄鋼・金属・鉱業")
MIndustry.create!(industry_name: "機械")
MIndustry.create!(industry_name: "プラント・エンジニアリング")
MIndustry.create!(industry_name: "自動車・輸送機器")
MIndustry.create!(industry_name: "電機・電子・ＯＡ関連・精密機器")
MIndustry.create!(industry_name: "家電・ＡＶ機器")
MIndustry.create!(industry_name: "ゲーム機器")
MIndustry.create!(industry_name: "事務機器・インテリア・文具")
MIndustry.create!(industry_name: "印刷関連")
MIndustry.create!(industry_name: "その他製造")
MIndustry.create!(industry_name: "総合商社")
MIndustry.create!(industry_name: "専門商社")
MIndustry.create!(industry_name: "百貨店")
MIndustry.create!(industry_name: "スーパー・コンビニエンスストア")
MIndustry.create!(industry_name: "専門店")
MIndustry.create!(industry_name: "銀行")
MIndustry.create!(industry_name: "信用金庫・信用組合・労働金庫")
MIndustry.create!(industry_name: "証券")
MIndustry.create!(industry_name: "生命保険")
MIndustry.create!(industry_name: "損害保険")
MIndustry.create!(industry_name: "クレジット・信販・リース")
MIndustry.create!(industry_name: "その他金融")
MIndustry.create!(industry_name: "ソフトウェア・情報処理")
MIndustry.create!(industry_name: "ゲームソフト")
MIndustry.create!(industry_name: "インターネット関連")
MIndustry.create!(industry_name: "通信")
MIndustry.create!(industry_name: "運輸")
MIndustry.create!(industry_name: "倉庫")
MIndustry.create!(industry_name: "不動産")
MIndustry.create!(industry_name: "コンサルタント")
MIndustry.create!(industry_name: "シンクタンク")
MIndustry.create!(industry_name: "電気・ガス・エネルギー")
MIndustry.create!(industry_name: "放送")
MIndustry.create!(industry_name: "広告")
MIndustry.create!(industry_name: "出版・新聞")
MIndustry.create!(industry_name: "ホテル・旅行")
MIndustry.create!(industry_name: "レジャー・エンタテインメント")
MIndustry.create!(industry_name: "レストラン・フード")
MIndustry.create!(industry_name: "医療")
MIndustry.create!(industry_name: "介護・福祉")
MIndustry.create!(industry_name: "教育サービス")
MIndustry.create!(industry_name: "人材サービス（派遣・斡旋等）")
MIndustry.create!(industry_name: "官公庁・公社・公団")
MIndustry.create!(industry_name: "その他サービス")
MIndustry.create!(industry_name: "未定")
#Industry data seed end (New Industry)

#welfares data seed start (New welfare)
MWelfare.create!(welfare_category: "住宅")
MWelfare.create!(welfare_category: "健康・医療")
MWelfare.create!(welfare_category: "慶弔・災害")
MWelfare.create!(welfare_category: "育児・介護")
MWelfare.create!(welfare_category: "教育・研修")
MWelfare.create!(welfare_category: "業務・職場環境・働き方")
MWelfare.create!(welfare_category: "休暇")
MWelfare.create!(welfare_category: "文化・体育・レクリエーション")
MWelfare.create!(welfare_category: "財産形成")
MWelfare.create!(welfare_category: "その他")
#welfares data seed end (New welfare)

#welfares details data seed start (New welfare list)
MWelfareDetail.create!(m_welfare_id: 1,welfare_type: "寮の提供")
MWelfareDetail.create!(m_welfare_id: 1,welfare_type: "借り上げ社宅の提供")
MWelfareDetail.create!(m_welfare_id: 1,welfare_type: "住宅ローン補助")
MWelfareDetail.create!(m_welfare_id: 1,welfare_type: "住宅手当（家賃補助）")
MWelfareDetail.create!(m_welfare_id: 1,welfare_type: "社宅")
MWelfareDetail.create!(m_welfare_id: 2,welfare_type: "健康診断（法定以上の項目）")
MWelfareDetail.create!(m_welfare_id: 2,welfare_type: "人間ドック")
MWelfareDetail.create!(m_welfare_id: 2,welfare_type: "相談窓口の設置")
MWelfareDetail.create!(m_welfare_id: 2,welfare_type: "カウンセラーの配属")
MWelfareDetail.create!(m_welfare_id: 2,welfare_type: "ジムやスポーツ活動に対する補助")
MWelfareDetail.create!(m_welfare_id: 2,welfare_type: "仮眠室の設置")
MWelfareDetail.create!(m_welfare_id: 2,welfare_type: "ウォーキング")
MWelfareDetail.create!(m_welfare_id: 2,welfare_type: "自転車通勤手当")
MWelfareDetail.create!(m_welfare_id: 2,welfare_type: "朝食の無料提供")
MWelfareDetail.create!(m_welfare_id: 3,welfare_type: "結婚祝い金")
MWelfareDetail.create!(m_welfare_id: 3,welfare_type: "従業員や家族の死亡時弔慰金")
MWelfareDetail.create!(m_welfare_id: 3,welfare_type: "従業員の子供の入学")
MWelfareDetail.create!(m_welfare_id: 3,welfare_type: "成人に対する祝い金")
MWelfareDetail.create!(m_welfare_id: 3,welfare_type: "災害見舞金")
MWelfareDetail.create!(m_welfare_id: 3,welfare_type: "遺族年金")
MWelfareDetail.create!(m_welfare_id: 4,welfare_type: "法定以上の育児介護休業、子の看護休暇日数")
MWelfareDetail.create!(m_welfare_id: 4,welfare_type: "短時間勤務制度")
MWelfareDetail.create!(m_welfare_id: 4,welfare_type: "男性従業員の育児休暇の充実")
MWelfareDetail.create!(m_welfare_id: 4,welfare_type: "パパママ育休プラス")
MWelfareDetail.create!(m_welfare_id: 4,welfare_type: "産休・育児休暇取得（実績あり）")
MWelfareDetail.create!(m_welfare_id: 4,welfare_type: "ベビーシッター料補助")
MWelfareDetail.create!(m_welfare_id: 5,welfare_type: "ラーニングや通信教育の提供や補助")
MWelfareDetail.create!(m_welfare_id: 5,welfare_type: "図書購入費補助")
MWelfareDetail.create!(m_welfare_id: 5,welfare_type: "資格取得支援、受験料補助")
MWelfareDetail.create!(m_welfare_id: 5,welfare_type: "講座、セミナー参加費補助")
MWelfareDetail.create!(m_welfare_id: 5,welfare_type: "海外研修、経験制度")
MWelfareDetail.create!(m_welfare_id: 6,welfare_type: "オフィス内食堂")
MWelfareDetail.create!(m_welfare_id: 6,welfare_type: "カフェの設置")
MWelfareDetail.create!(m_welfare_id: 6,welfare_type: "集中できる個別スペースの設置")
MWelfareDetail.create!(m_welfare_id: 6,welfare_type: "ニーズに合わせたスキルアップ研修の実施")
MWelfareDetail.create!(m_welfare_id: 6,welfare_type: "シエスタ制度、マッサージ利用制度")
MWelfareDetail.create!(m_welfare_id: 6,welfare_type: "在宅勤務、テレワークの導入")
MWelfareDetail.create!(m_welfare_id: 6,welfare_type: "従業員間での感謝貢献ポイントのやり取り")
MWelfareDetail.create!(m_welfare_id: 6,welfare_type: "完全週休2日制")
MWelfareDetail.create!(m_welfare_id: 6,welfare_type: "平均残業時間が月20時間以内")
MWelfareDetail.create!(m_welfare_id: 6,welfare_type: "副業・起業支援制度")
MWelfareDetail.create!(m_welfare_id: 6,welfare_type: "ジョブローテーション制度")
MWelfareDetail.create!(m_welfare_id: 7,welfare_type: "年間休日120日以上")
MWelfareDetail.create!(m_welfare_id: 7,welfare_type: "法定日数以上の有給休暇")
MWelfareDetail.create!(m_welfare_id: 7,welfare_type: "リフレッシュ休暇")
MWelfareDetail.create!(m_welfare_id: 7,welfare_type: "アニバーサリー休暇")
MWelfareDetail.create!(m_welfare_id: 7,welfare_type: "生理休暇")
MWelfareDetail.create!(m_welfare_id: 7,welfare_type: "失恋休暇")
MWelfareDetail.create!(m_welfare_id: 7,welfare_type: "育自分休暇制度（最長6年）")
MWelfareDetail.create!(m_welfare_id: 8,welfare_type: "スポーツ部活動や文化サークル活動の補助金")
MWelfareDetail.create!(m_welfare_id: 8,welfare_type: "ランチや飲み会の費用補助")
MWelfareDetail.create!(m_welfare_id: 8,welfare_type: "運動施設保養所利用の割引補助")
MWelfareDetail.create!(m_welfare_id: 8,welfare_type: "イベント開催費の補助")
MWelfareDetail.create!(m_welfare_id: 8,welfare_type: "社員旅行")
MWelfareDetail.create!(m_welfare_id: 9,welfare_type: "確定給付企業年金制度")
MWelfareDetail.create!(m_welfare_id: 9,welfare_type: "財形貯蓄制度")
MWelfareDetail.create!(m_welfare_id: 9,welfare_type: "持株会の実施")
MWelfareDetail.create!(m_welfare_id: 9,welfare_type: "社内預金制度")
MWelfareDetail.create!(m_welfare_id: 9,welfare_type: "資格インセンティブ制")
MWelfareDetail.create!(m_welfare_id: 9,welfare_type: "確定拠出年金制度")
MWelfareDetail.create!(m_welfare_id: 10,welfare_type: "食事補助など")
#welfares details data seed end (New welfare list)

#Qualification  data seed Strat (New Qualification)
MQualification.create!(qualification_category: "経済・経営・会計")
MQualification.create!(qualification_category: "教職")
MQualification.create!(qualification_category: "法律")
MQualification.create!(qualification_category: "医療・介護・福祉・保育")
MQualification.create!(qualification_category: "情報処理")
MQualification.create!(qualification_category: "コンピュータおよびネットワーク")
MQualification.create!(qualification_category: "技術")
MQualification.create!(qualification_category: "その他")
MQualification.create!(qualification_category: "その他、民間資格　正式名称")
#Qualification  data seed End (New Qualification)

#Qualification List  data seed Start (New Qualification List)
MQualificationDetail.create!(m_qualification_id: 1,qualification_type: "経済・経営・会計")
MQualificationDetail.create!(m_qualification_id: 1,qualification_type: "公認会計士")
MQualificationDetail.create!(m_qualification_id: 1,qualification_type: "ファイナンシャル・プランナー")
MQualificationDetail.create!(m_qualification_id: 1,qualification_type: "日商簿記1級")
MQualificationDetail.create!(m_qualification_id: 1,qualification_type: "日商簿記2級")
MQualificationDetail.create!(m_qualification_id: 1,qualification_type: "中小企業診断士")
MQualificationDetail.create!(m_qualification_id: 1,qualification_type: "社会保険労務士")
MQualificationDetail.create!(m_qualification_id: 1,qualification_type: "税理士")
MQualificationDetail.create!(m_qualification_id: 1,qualification_type: "MBA取得（予定）")
MQualificationDetail.create!(m_qualification_id: 2,qualification_type: "教員免許取得（予定）")
MQualificationDetail.create!(m_qualification_id: 3,qualification_type: "司法書士")
MQualificationDetail.create!(m_qualification_id: 3,qualification_type: "行政書士")
MQualificationDetail.create!(m_qualification_id: 4,qualification_type: "薬剤師")
MQualificationDetail.create!(m_qualification_id: 4,qualification_type: "管理栄養士")
MQualificationDetail.create!(m_qualification_id: 4,qualification_type: "臨床検査技師")
MQualificationDetail.create!(m_qualification_id: 4,qualification_type: "看護師")
MQualificationDetail.create!(m_qualification_id: 4,qualification_type: "実務者・介護職員初任者研修")
MQualificationDetail.create!(m_qualification_id: 4,qualification_type: "介護福祉士")
MQualificationDetail.create!(m_qualification_id: 4,qualification_type: "社会福祉士")
MQualificationDetail.create!(m_qualification_id: 4,qualification_type: "作業療法士")
MQualificationDetail.create!(m_qualification_id: 4,qualification_type: "理学療法士")
MQualificationDetail.create!(m_qualification_id: 4,qualification_type: "保育士")
MQualificationDetail.create!(m_qualification_id: 5,qualification_type: "ITパスポート（旧 初級システムアドミニストレータ）")
MQualificationDetail.create!(m_qualification_id: 5,qualification_type: "基本情報技術者")
MQualificationDetail.create!(m_qualification_id: 5,qualification_type: "応用情報技術者（旧 ソフトウェア開発技術者）")
MQualificationDetail.create!(m_qualification_id: 5,qualification_type: "ITストラテジスト")
MQualificationDetail.create!(m_qualification_id: 5,qualification_type: "システムアーキテクト")
MQualificationDetail.create!(m_qualification_id: 5,qualification_type: "プロジェクトマネージャ")
MQualificationDetail.create!(m_qualification_id: 5,qualification_type: "ネットワークスペシャリスト")
MQualificationDetail.create!(m_qualification_id: 5,qualification_type: "データベーススペシャリスト")
MQualificationDetail.create!(m_qualification_id: 5,qualification_type: "エンベデッドシステムスペシャリスト")
MQualificationDetail.create!(m_qualification_id: 5,qualification_type: "情報セキュリティスペシャリスト")
MQualificationDetail.create!(m_qualification_id: 5,qualification_type: "ITサービスマネージャ")
MQualificationDetail.create!(m_qualification_id: 5,qualification_type: "システム監査技術者")
MQualificationDetail.create!(m_qualification_id: 6,qualification_type: "マイクロソフト認定トレーナー（MCT）")
MQualificationDetail.create!(m_qualification_id: 6,qualification_type: "マイクロソフト オフィス スペシャリスト（MOS）")
MQualificationDetail.create!(m_qualification_id: 6,qualification_type: "マイクロソフト認定資格プログラム（MCP）")
MQualificationDetail.create!(m_qualification_id: 6,qualification_type: "オラクルマスター")
MQualificationDetail.create!(m_qualification_id: 6,qualification_type: "日商PC検定")
MQualificationDetail.create!(m_qualification_id: 6,qualification_type: "DTPエキスパート")
MQualificationDetail.create!(m_qualification_id: 6,qualification_type: "シスコ技術者認定")
MQualificationDetail.create!(m_qualification_id: 6,qualification_type: "JavaTMプログラミング能力認定")
MQualificationDetail.create!(m_qualification_id: 6,qualification_type: "UMLモデリング技能認定")
MQualificationDetail.create!(m_qualification_id: 6,qualification_type: "CIW Web Foundations Associate")
MQualificationDetail.create!(m_qualification_id: 7,qualification_type: "一級建築士")
MQualificationDetail.create!(m_qualification_id: 7,qualification_type: "二級建築士")
MQualificationDetail.create!(m_qualification_id: 7,qualification_type: "CAD利用技術者")
MQualificationDetail.create!(m_qualification_id: 7,qualification_type: "電気主任技術者")
MQualificationDetail.create!(m_qualification_id: 8,qualification_type: "各種自動車運転免許")
MQualificationDetail.create!(m_qualification_id: 8,qualification_type: "不動産鑑定士")
MQualificationDetail.create!(m_qualification_id: 8,qualification_type: "宅地建物取引士（旧：宅地建物取引主任者）")
MQualificationDetail.create!(m_qualification_id: 8,qualification_type: "通関士")
MQualificationDetail.create!(m_qualification_id: 8,qualification_type: "総合旅行業務取扱管理者")
MQualificationDetail.create!(m_qualification_id: 8,qualification_type: "気象予報士")
MQualificationDetail.create!(m_qualification_id: 8,qualification_type: "獣医師")
MQualificationDetail.create!(m_qualification_id: 8,qualification_type: "秘書技能検定")
MQualificationDetail.create!(m_qualification_id: 8,qualification_type: "普通自動車免許")
MQualificationDetail.create!(m_qualification_id: 8,qualification_type: "大型自動車免許")
MQualificationDetail.create!(m_qualification_id: 8,qualification_type: "普通自動二輪車免許")
MQualificationDetail.create!(m_qualification_id: 8,qualification_type: "大型自動二輪車免許")
#Qualification List  data seed End (New Qualification List)

#Job Category List  data seed for job_categories table start (New Job Category List)
MOccupation.create!(occupation_name: "商品企画・プランニング")
MOccupation.create!(occupation_name: "調査・マーケティング")
MOccupation.create!(occupation_name: "一般事務・営業事務")
MOccupation.create!(occupation_name: "総務・業務")
MOccupation.create!(occupation_name: "人事・労務")
MOccupation.create!(occupation_name: "財務・会計・経理")
MOccupation.create!(occupation_name: "宣伝・広報")
MOccupation.create!(occupation_name: "貿易事務・国際事務")
MOccupation.create!(occupation_name: "法務・審査・特許")
MOccupation.create!(occupation_name: "販売促進・営業推進")
MOccupation.create!(occupation_name: "経営企画")
MOccupation.create!(occupation_name: "営業（個人向け・新規開拓中心）")
MOccupation.create!(occupation_name: "営業（個人向け・得意先中心）")
MOccupation.create!(occupation_name: "営業（企業向け・新規開拓中心）")
MOccupation.create!(occupation_name: "営業（企業向け・得意先中心）")
MOccupation.create!(occupation_name: "MR（医薬情報担当者）")
MOccupation.create!(occupation_name: "技術営業・システム営業")
MOccupation.create!(occupation_name: "販売・サービススタッフ")
MOccupation.create!(occupation_name: "店長（店舗経営など）")
MOccupation.create!(occupation_name: "スーパーバイザー")
MOccupation.create!(occupation_name: "バイヤー")
MOccupation.create!(occupation_name: "店舗開発")
MOccupation.create!(occupation_name: "システムアナリスト・コンサルタント")
MOccupation.create!(occupation_name: "システムエンジニア（SE）")
MOccupation.create!(occupation_name: "ネットワークエンジニア")
MOccupation.create!(occupation_name: "プログラマー")
MOccupation.create!(occupation_name: "セールスエンジニア")
MOccupation.create!(occupation_name: "カスタマーエンジニア")
MOccupation.create!(occupation_name: "システム運用・保守")
MOccupation.create!(occupation_name: "Webプロデューサー・ディレクター")
MOccupation.create!(occupation_name: "基礎研究")
MOccupation.create!(occupation_name: "応用研究・技術開発")
MOccupation.create!(occupation_name: "生産・製造技術開発")
MOccupation.create!(occupation_name: "機械・電機・電子機器設計")
MOccupation.create!(occupation_name: "生産管理・品質管理・メンテナンス")
MOccupation.create!(occupation_name: "物流・在庫管理")
MOccupation.create!(occupation_name: "建築・土木技術者")
MOccupation.create!(occupation_name: "施工管理")
MOccupation.create!(occupation_name: "トレーダー・ディーラー")
MOccupation.create!(occupation_name: "融資・資産運用（ファンドマネージャーなど）")
MOccupation.create!(occupation_name: "証券アナリスト")
MOccupation.create!(occupation_name: "アクチュアリー")
MOccupation.create!(occupation_name: "コンサルタント・研究員")
MOccupation.create!(occupation_name: "講師・インストラクター")
MOccupation.create!(occupation_name: "教師")
MOccupation.create!(occupation_name: "保育士")
MOccupation.create!(occupation_name: "栄養士・管理栄養士")
MOccupation.create!(occupation_name: "アナウンサー")
MOccupation.create!(occupation_name: "薬剤師")
MOccupation.create!(occupation_name: "看護師")
MOccupation.create!(occupation_name: "医療技師（臨床検査技師など）")
MOccupation.create!(occupation_name: "介護福祉士")
MOccupation.create!(occupation_name: "社会福祉士")
MOccupation.create!(occupation_name: "ホームヘルパー")
MOccupation.create!(occupation_name: "作業療法士（OT）")
MOccupation.create!(occupation_name: "理学療法士（PT）")
MOccupation.create!(occupation_name: "編集・制作")
MOccupation.create!(occupation_name: "記者・ライター")
MOccupation.create!(occupation_name: "デザイナー")
MOccupation.create!(occupation_name: "ゲームクリエイター")
MOccupation.create!(occupation_name: "国家公務員")
MOccupation.create!(occupation_name: "地方公務員")
MOccupation.create!(occupation_name: "警察官・自衛官")
MOccupation.create!(occupation_name: "その他公務員・団体職員")
MOccupation.create!(occupation_name: "未定")
#Job Category List  data seed for job_categories table End (New Job Category List)

#Location List  data seed for locations table Start (New Job Location List)
MRegion.create!(region_name: "どこでも可能")
MRegion.create!(region_name: "北海道")
MRegion.create!(region_name: "東北地方")
MRegion.create!(region_name: "関東地方")
MRegion.create!(region_name: "中部地方")
MRegion.create!(region_name: "関西地方")
MRegion.create!(region_name: "中国地方")
MRegion.create!(region_name: "四国")
MRegion.create!(region_name: "九州")
MRegion.create!(region_name: "海外")
MRegion.create!(region_name: "未定")
#Location List  data seed for locations table End (New Job Location List)

#CommitmentAbility data seed start
MCommitmentAbility.create!(name: "物事に進んで取り組む力")
MCommitmentAbility.create!(name: "変化に前向きに対処する⼒")
MCommitmentAbility.create!(name: "範囲を限定せず主体的に動く力")
MCommitmentAbility.create!(name: "他人を巻き込む能力")
MCommitmentAbility.create!(name: "多様な人達と繋がる力")
MCommitmentAbility.create!(name: "多様性を活かす対話力")
MCommitmentAbility.create!(name: "異文化を受け入れる力")
MCommitmentAbility.create!(name: "関係構築能力")
MCommitmentAbility.create!(name: "やりきる力")
MCommitmentAbility.create!(name: "組織に隷属せず高い志を持つこと")
MCommitmentAbility.create!(name: "一人で考え抜く力")
MCommitmentAbility.create!(name: "新しい問題を発見する力")
MCommitmentAbility.create!(name: "システムとして物事を考える力")
MCommitmentAbility.create!(name: "⾼い倫理観を持ち正しい選択をする⼒")
MCommitmentAbility.create!(name: "未来を予想する力")
MCommitmentAbility.create!(name: "抽象的に思考する能力")
MCommitmentAbility.create!(name: "芸術的な感性")
MCommitmentAbility.create!(name: "価値を判断する能力")
MCommitmentAbility.create!(name: "自分の意見を分かりやすく伝える力")
MCommitmentAbility.create!(name: "相手の意見を丁寧に聴く力")
MCommitmentAbility.create!(name: "意見の違いや相手の立場を理解する力")
MCommitmentAbility.create!(name: "自分と周囲の人々や物事との関係性を理解する力")
MCommitmentAbility.create!(name: "社会のルールや人との約束を守る力")
MCommitmentAbility.create!(name: "ストレスの発生源に対応する力")
#CommitmentAbility data seed end